version: '3.8'
services:
  server:
    image: server-heart-image
    build:
      context: .
      dockerfile: .docker/Dockerfile.server
  client:
    image: client-heart-image
    build:
      context: .
      dockerfile: .docker/Dockerfile.client
  donation:
    image: donation-heart-image
    build:
      context: .
      dockerfile: .docker/Dockerfile.donation
  proxy:
    image: proxy-heart-image
    build:
      context: . 
      dockerfile: .docker/Dockerfile.proxy

  