# Builder
FROM node:alpine as builder
WORKDIR .
COPY ../client ./client
COPY ../types ./types
RUN cd /client && yarn
RUN cd /types && yarn
RUN cd /client && yarn build

# Production
FROM nginx:alpine
COPY --from=builder /client/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /client/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
